#services:
#  jenkins:
#    build: .
#    container_name: jenkins
#    ports:
#      - "9090:8080"
#    volumes:
#      - jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#    privileged: true
#
#  spring-app:
#    image: springio/gs-spring-boot-docker
#    container_name: spring-application
#    ports:
#      - "8081:8080"
#    restart: unless-stopped
#
#volumes:
#  jenkins_home:



version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    user: root


  spring-app:
    image: springio/gs-spring-boot-docker
    container_name: spring-application
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - jenkins-net
    depends_on:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge