services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "9090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  spring-app:
    image: springio/gs-spring-boot-docker
    container_name: spring-application
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  jenkins_home: